### PR TITLE
DEP: update mafft pin

### PR DESCRIPTION
**Pull request by thermokarst**

### CODE REVIEW

**Comment by thermokarst** [comment]
Cross reference: https://github.com/qiime2/q2-alignment/pull/68

**Comment by thermokarst** [comment]
Man, travis is barfing on skbio && pandas 1.0 && biom-format --- we need to sort out pandas and biom...

**Comment by wasade** [comment]
Pandas 1.0 had issues with sparse support so we weren't able to readily support it in biom. More detail in biocore/biom-format#838

**Comment by thermokarst** [comment]
Thanks @wasade, that was actually the PR I had in mind! Sorting that out is pretty high on our todo list - this biom issue is blocking QIIME 2 from adopting pandas 1.0 at the moment. I'll continue this discussion over on https://github.com/biocore/biom-format.

**Comment by thermokarst** [comment]
Superseded by https://github.com/biocore/deblur/pull/212

**Pull request closed without merging**
