### PR TITLE
BUGFIX: default negative database was set incorrectly

### PR DESCRIPTION
**Pull request by amnona**
Please merge fast :)

### CODE REVIEW

**Comment by mortonjt** [comment]
whoa.  how did we miss that haha

**Comment by antgonza** [comment]
Wow!! I'm also impress that the tests didn't catch that and/or that tests don't need to change ... Fine to merge after we understand why tests don't need to change or they are changed.

**Comment by wasade** [comment]
Given this, can a regression test be added?

**Comment by mortonjt** [comment]
Agree. We should add a test to make sure this doesn't happen again

**Comment by wasade** [comment]
Please add a detailed mention of the problem into the CHANGELOG, and this should trigger a minor version release

**Pull request merged**
